# Automatically builds and publishes the mod when a new release is created on GitHub.
# It uploads the mod to GitHub, CurseForge and Modrinth.

name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish mod to GitHub, CurseForge and Modrinth
        id: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          changelog: ${{ github.event.release.body }}
          java: 17

          modrinth-featured: true
          modrinth-unfeature-mode: subset
          loaders: |
            fabric
            forge
            quilt
